[project]
name = "mcp-ollama-local"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.126.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.25.0",
    "uvicorn>=0.40.0",
]
